# Generated by Django 2.1.5 on 2019-02-05 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.IntegerField()),
                ('fname', models.CharField(max_length=20)),
                ('sname', models.CharField(max_length=20)),
            ],
        ),
    ]
